### ISSUE TITLE
Latest / 4.1.0 build exits

### ISSUE THREAD

**Issue by gusmeister** [Ortus-Solutions/docker-contentbox#2]
Hi Gavin, 

I'm looking to spin up a 4.1 container to do some debugging on our environment. 

When I try and run ortussolutions/contentbox:latest or ortussolutions/contentbox:4.1.0 the build stops and exits after a few steps.

Console log:

Pulling contentbox (ortussolutions/contentbox:latest)...
latest: Pulling from ortussolutions/contentbox
Recreating cb_site ... 

Recreating cb_site ... done
Attaching to cb_site
cb_site       | INFO: Express installation specified.  Configuring H2 Database.
cb_site       | INFO: H2 Database set to /data/contentbox/db
cb_site       | INFO: Contentbox media root set as /app/modules_app/contentbox-custom/_content
cb_site exited with code 0

Any ideas?

Thanks
Angus

**Comment by lmajano** [comment]
Can you post the commands you used please

**Comment by gusmeister** [comment]
Hi Luis,

Command: docker run -p 8099:8080 -e EXPRESS=true -e INSTALL=true ortussolutions/contentbox:latest

I have the same result if I try /contentbox:4.1.0 or just /contentbox. 

The :lucee45 and :lucee5 production images spin up fine. 

I also tried :snapshot but it exits early.

Cheers
Angus

docker version
Client: Docker Engine - Community
 Version:           18.09.0
 API version:       1.39
 Go version:        go1.10.4
 Git commit:        4d60db4
 Built:             Wed Nov  7 00:47:51 2018
 OS/Arch:           windows/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.0
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.4
  Git commit:       4d60db4
  Built:            Wed Nov  7 00:55:00 2018
  OS/Arch:          linux/amd64
  Experimental:     false

**Comment by lmajano** [comment]
I have not forgotten about this, holidays got in the way.

**Comment by lmajano** [comment]
I have found the issues, the new release will be today
